In [4]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [5]:
df = pd.read_csv('./Country-data.csv')

In [6]:
columns_names=df.columns.tolist()
print("Columns names:")
print(columns_names)

Columns names:
['country', 'child_mort', 'exports', 'health', 'imports', 'income', 'inflation', 'life_expec', 'total_fer', 'gdpp']


In [7]:
df.shape

(167, 10)

In [8]:
df.head()

country  child_mort  exports  health  imports  income  \
0          Afghanistan        90.2     10.0    7.58     44.9    1610   
1              Albania        16.6     28.0    6.55     48.6    9930   
2              Algeria        27.3     38.4    4.17     31.4   12900   
3               Angola       119.0     62.3    2.85     42.9    5900   
4  Antigua and Barbuda        10.3     45.5    6.03     58.9   19100   

   inflation  life_expec  total_fer   gdpp  
0       9.44        56.2       5.82    553  
1       4.49        76.3       1.65   4090  
2      16.10        76.5       2.89   4460  
3      22.40        60.1       6.16   3530  
4       1.44        76.8       2.13  12200

In [9]:
df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
       'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros',
       'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cyprus', 'Czech Republic', 'Denmark',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Fiji', 'Finland',
       'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
       'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran

In [10]:
df_drop=df.drop(labels=['country','gdpp', 'total_fer'],axis=1)
df_drop.head()

child_mort  exports  health  imports  income  inflation  life_expec
0        90.2     10.0    7.58     44.9    1610       9.44        56.2
1        16.6     28.0    6.55     48.6    9930       4.49        76.3
2        27.3     38.4    4.17     31.4   12900      16.10        76.5
3       119.0     62.3    2.85     42.9    5900      22.40        60.1
4        10.3     45.5    6.03     58.9   19100       1.44        76.8

In [11]:
cols = df_drop.columns.tolist()
cols

['child_mort',
 'exports',
 'health',
 'imports',
 'income',
 'inflation',
 'life_expec']

In [12]:
X = df_drop.iloc[:,1:7].values
y = df_drop.iloc[:,0].values
X

array([[1.00e+01, 7.58e+00, 4.49e+01, 1.61e+03, 9.44e+00, 5.62e+01],
       [2.80e+01, 6.55e+00, 4.86e+01, 9.93e+03, 4.49e+00, 7.63e+01],
       [3.84e+01, 4.17e+00, 3.14e+01, 1.29e+04, 1.61e+01, 7.65e+01],
       ...,
       [7.20e+01, 6.84e+00, 8.02e+01, 4.49e+03, 1.21e+01, 7.31e+01],
       [3.00e+01, 5.18e+00, 3.44e+01, 4.48e+03, 2.36e+01, 6.75e+01],
       [3.70e+01, 5.89e+00, 3.09e+01, 3.28e+03, 1.40e+01, 5.20e+01]])

In [13]:
np.shape(X)

(167, 6)

In [14]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)
X_std

array([[-1.13827979,  0.27908825, -0.08245496, -0.8082454 ,  0.15733622,
        -1.61909203],
       [-0.47965843, -0.09701618,  0.07083669, -0.3753689 , -0.31234747,
         0.64786643],
       [-0.09912164, -0.96607302, -0.64176233, -0.22084447,  0.78927429,
         0.67042323],
       ...,
       [ 1.13030491,  0.0088773 ,  1.38003025, -0.65840354,  0.40973191,
         0.28695762],
       [-0.40647827, -0.59727159, -0.5174718 , -0.65892382,  1.50091625,
        -0.34463279],
       [-0.15034774, -0.33801514, -0.66247742, -0.72135793,  0.59001454,
        -2.09278484]])

In [15]:
X_meaned = X_std - np.mean(X_std , axis = 0)
print('X_meaned: ',X_meaned)
print('------------------------------------------------------------------------------------------------------------------------------------')

print('X.shape: ', X.shape)
print('------------------------------------------------------------------------------------------------------------------------------------')
print('X_meaned.shape: ', X_meaned.shape)
print('------------------------------------------------------------------------------------------------------------------------------------')

cov_mat = np.cov(X_meaned , rowvar = False)   # rowvar = False >> work with X_meaned as transposed

print('cov_mat.shape: ',cov_mat.shape)
print('------------------------------------------------------------------------------------------------------------------------------------')

print('cov_mat: ',cov_mat)
print('------------------------------------------------------------------------------------------------------------------------------------')

eigen_values , eigen_vectors = np.linalg.eigh(cov_mat)

print('eigen_vectors.shape: ',eigen_vectors.shape)
print('------------------------------------------------------------------------------------------------------------------------------------')

print('eigen_values: ',eigen_values)
print('------------------------------------------------------------------------------------------------------------------------------------')


#sort the eigenvalues in descending order
sorted_index = np.argsort(eigen_values)[::-1]
print('sorted_index: ', sorted_index)
print('------------------------------------------------------------------------------------------------------------------------------------')

sorted_eigenvalue = eigen_values[sorted_index]
#similarly sort the eigenvectors 
sorted_eigenvectors = eigen_vectors[:,sorted_index]
n_components = 2 #you can select any number of components.
eigenvector_subset = sorted_eigenvectors[:,0:n_components]
print('eigenvector_subset: ',eigenvector_subset)
print('------------------------------------------------------------------------------------------------------------------------------------')

X_reduced = np.dot(eigenvector_subset.transpose(),X_meaned.transpose()).transpose()
print('X_reduced: ', X_reduced)
print('------------------------------------------------------------------------------------------------------------------------------------')
print('X_reduced shape: ', X_reduced.shape)


X_meaned:  [[-1.13827979  0.27908825 -0.08245496 -0.8082454   0.15733622 -1.61909203]
 [-0.47965843 -0.09701618  0.07083669 -0.3753689  -0.31234747  0.64786643]
 [-0.09912164 -0.96607302 -0.64176233 -0.22084447  0.78927429  0.67042323]
 ...
 [ 1.13030491  0.0088773   1.38003025 -0.65840354  0.40973191  0.28695762]
 [-0.40647827 -0.59727159 -0.5174718  -0.65892382  1.50091625 -0.34463279]
 [-0.15034774 -0.33801514 -0.66247742 -0.72135793  0.59001454 -2.09278484]]
------------------------------------------------------------------------------------------------------------------------------------
X.shape:  (167, 6)
------------------------------------------------------------------------------------------------------------------------------------
X_meaned.shape:  (167, 6)
------------------------------------------------------------------------------------------------------------------------------------
cov_mat.shape:  (6, 6)
------------------------------------------------------------------

In [16]:
def euclidean_distance(point1,point2):
    dis=0
    for i in range(len(point1)):
        dis+=(point1[i]-point2[i])**2
    return dis**0.5

In [17]:
g=2   
n=len(X_reduced)
c=3 #no. clusters
p=len(X_reduced[0])
max_iter=10
n,p

(167, 2)

In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import operator
import math
import random
from scipy.linalg import norm
from scipy.spatial.distance import cdist
from collections import defaultdict
from sklearn import datasets
from sklearn.datasets import make_blobs
import warnings
import os, cv2, json

def initialize_membership_matrix(n,c):
    member_mat=list()
    for i in range(n):
        random_list=[random.random() for x in range(c)]
        summation=sum(random_list)
        for i in range(len(random_list)):
            random_list[i]=random_list[i]/summation
        member_mat.append(random_list)
    return member_mat

def update_centroid(member_mat):
    centroids={}

    for j in range(c):
        temp=[]
        for k in range(p):
            
            add=0
            for i in range(n):
                add+=member_mat[i][j]**g
            x=0
            for i in range(n):
                x+=(member_mat[i][j]**g)*(X_reduced[i][k])
            val=x/add
            temp.append(val)
        centroids[j]=temp
    return centroids


def update_membership_matrix(member_mat,centroids):
    ratio=float(2/(g-1))

    for i in range(n):
        distances=list()
        for j in range(c):
            distances.append(euclidean_distance(X_reduced[i],centroids[j]))
        for j in range(c):
            den = sum([math.pow(float(distances[j]/distances[q]), ratio) for q in range(c)])
            member_mat[i][j] = float(1/den) 
           
            
    return member_mat
        
                
    
def find_cluster(member_mat):
    clusters=list()
    for i in range(n):
        max_val, idx = max((val, idx) for (idx, val) in enumerate(member_mat[i]))
        clusters.append(idx)
    return clusters

def check(old_member_mat,member_mat):
    diff=0
    for i in range(n):
        for j in range(c):
            diff+=old_member_mat[i][j]-member_mat[i][j]               #old_member_mat---------> initialize_membership_matrix
    if(diff<0.01):
        return True
    return False

def fuzzy_c_mean():
    
    member_mat=initialize_membership_matrix(n,c)
    for i in range(max_iter):
        centroids=update_centroid(member_mat)
        old_member_mat=member_mat
        member_mat=update_membership_matrix(member_mat,centroids)
        cluster=find_cluster(member_mat)
        if(check(old_member_mat,member_mat))<0.01:
            print(i)
            break
    
   
    
    return cluster,centroids



In [19]:
clusters,centroids=fuzzy_c_mean()
print("Final Centroid points are:")
print(centroids)


# labeling the clusters
def label_clusters(clusters):
    z=0
    o=0
    t=0
    dict=defaultdict(int)


    for i in range(50):
        if(clusters[i]==0):
            z=z+1
        elif(clusters[i]==1):
            o=o+1
        else:
            t=t+1
    dict[z]=0
    dict[o]=1
    dict[t]=2
    classes=[]
    fin1=max(z,max(o,t))
    
    classes.append(dict[fin1])
    z=0
    o=0
    t=0
    for i in range(50,100):
        if(clusters[i]==0):
            z=z+1
        elif(clusters[i]==1):
            o=o+1
        else:
            t=t+1
    dict[z]=0
    dict[o]=1
    dict[t]=2

    fin1=max(z,max(o,t))
    
    classes.append(dict[fin1])
    z=0
    o=0
    t=0
    for i in range(100,150):
        if(clusters[i]==0):
            z=z+1
        elif(clusters[i]==1):
            o=o+1
        else:
            t=t+1
    dict[z]=0
    dict[o]=1
    dict[t]=2
    fin1=max(z,max(o,t))
   
    classes.append(dict[fin1])
    
    return classes

classes=label_clusters(clusters)

Final Centroid points are:
{0: [-1.1889563558055938, -1.1680310667813603], 1: [1.244068608355146, 0.27936076129964094], 2: [-0.4841544559365831, 0.4847138615541293]}


In [20]:


def confusion_matrix(clusters,classes,labels):
    c_matrix=[[0 for i in range(labels)] for j in range(labels)]
    m=0
    n=0
    q=0
    for i in range(50):

        if clusters[i]==classes[0]:
            m=m+1
        elif clusters[i]==classes[1]:
            n=n+1
        else:
            q=q+1
    c_matrix[0][0]=m
    c_matrix[0][1]=n
    c_matrix[0][2]=q
    m=0
    n=0
    q=0
    for i in range(50,100):
        if clusters[i]==classes[0]:
            m=m+1
        elif clusters[i]==classes[1]:
            n=n+1
        else:
            q=q+1
    c_matrix[1][0]=m
    c_matrix[1][1]=n
    c_matrix[1][2]=q
    m=0
    n=0
    q=0

    for i in range(100,150):
        if clusters[i]==classes[0]:
            m=m+1
        elif clusters[i]==classes[1]:
            n=n+1
        else:
            q=q+1
    c_matrix[2][0]=m
    c_matrix[2][1]=n
    c_matrix[2][2]=q
    
    
    return c_matrix
    



In [21]:
class Metrics:
    
    def __init__(self,confusion_m):
        self.confusion_m=confusion_m
        self.total=np.sum(confusion_m)
        self.diagonal=np.sum(np.diag(confusion_m))
    
    def accuracy(self):
        accuracy=(self.diagonal/self.total)
        return accuracy
    
    def recall(self):
        recall=np.diag(self.confusion_m)/np.sum(self.confusion_m,axis=1)
        recall=np.mean(recall)
        return recall
    
    def precision(self):
        precision=np.diag(self.confusion_m)/np.sum(self.confusion_m,axis=0)
        precision=np.mean(precision)
        
        return precision
    
    def f1_score(self,precision,recall):
        f1_score=(2*precision*recall)/(precision+recall)
        
        return f1_score

In [22]:
matrix=confusion_matrix(clusters,classes,3)
performance=Metrics(matrix)

accuracy=performance.accuracy()
recall=performance.recall()
precision=performance.precision()
f1_score=performance.f1_score(precision,recall)



In [24]:
print('Making Calculations... ')
print('------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
print("After USING PCA...")
print('------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')

A=initialize_membership_matrix(n,c)
print('initialize_membership_matrix: ',A ,end='\n')
print(' the_shape_of_initializing_membership_matrix:', len(A),end='\n')
print('------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
print('------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')

B=update_centroid(initialize_membership_matrix(n,c))
print('centroids are: ', B ,end='\n')       
print(' the_shape_of_centroids:', len(B),end='\n')

print('------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
print('------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')

C=update_membership_matrix(A,B)
print('update_membership_matrix: ',C ,end='\n')
print(' the_shape_of_updating_membership_matrix:', len(C),end='\n')

print('------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
print('------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')

D=find_cluster(C)
print('find_cluster: ',D ,end='\n')
print(' the_shape_of_clusters:', len(D),end='\n')

print('------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
print('------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')

print('confusion matrix is:',end='\n')
print(np.array(matrix),end='\n')
print('------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')


print("Accuracy of the model is {}".format(accuracy*100))
print('------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')

print("Recall of the model is {}".format(recall*100))
print('------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')

print("Precision of the model is {}".format(precision*100))
print('------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')

print("F1-Score of the model is {}".format(f1_score*100))
print('------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')

data = pd.DataFrame(X_reduced  )
data['cluster'] = D

Making Calculations... 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
After USING PCA...
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
initialize_membership_matrix:  [[0.3483871308963118, 0.3413038776020861, 0.3103089915016021], [0.28868232257607757, 0.36465625428370246, 0.34666142314021997], [0.3612098787341056, 0.31229014785462744, 0.3264999734112669], [0.47452937293972774, 0.06717801884294634, 0.4582926082173259], [0.4210657260935897, 0.25670681748676183, 0.3222274564196484], [0.31800787495932825, 0.27788051251271667, 0.4041116125279552], [0.07810569367443036, 0.08290017996441695, 0.8389941263611527], [0.03792170007145188, 0.1900933589

In [25]:
print('FCM_After_PCA with clusters')
data.head()

FCM_After_PCA with clusters


0         1  cluster
0  1.754824  0.139663        1
1  0.051140 -0.402060        0
2  0.506724  0.188814        1
3  1.080345  2.043346        1
4 -0.780608 -0.008174        0