In [19]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [20]:
df = pd.read_csv('./Country-data.csv')

In [21]:
columns_names=df.columns.tolist()
print("Columns names:")
print(columns_names)

Columns names:
['country', 'child_mort', 'exports', 'health', 'imports', 'income', 'inflation', 'life_expec', 'total_fer', 'gdpp']


In [22]:
df.shape

(167, 10)

In [23]:
df.head()

country  child_mort  exports  health  imports  income  \
0          Afghanistan        90.2     10.0    7.58     44.9    1610   
1              Albania        16.6     28.0    6.55     48.6    9930   
2              Algeria        27.3     38.4    4.17     31.4   12900   
3               Angola       119.0     62.3    2.85     42.9    5900   
4  Antigua and Barbuda        10.3     45.5    6.03     58.9   19100   

   inflation  life_expec  total_fer   gdpp  
0       9.44        56.2       5.82    553  
1       4.49        76.3       1.65   4090  
2      16.10        76.5       2.89   4460  
3      22.40        60.1       6.16   3530  
4       1.44        76.8       2.13  12200

In [24]:
df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
       'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros',
       'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cyprus', 'Czech Republic', 'Denmark',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Fiji', 'Finland',
       'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
       'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran

In [25]:
country=df.groupby('country').sum()


In [26]:
df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
       'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros',
       'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cyprus', 'Czech Republic', 'Denmark',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Fiji', 'Finland',
       'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
       'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran

In [27]:
groupby_country=df.groupby('country').mean()
groupby_country

child_mort  exports  health  imports   income  inflation  \
country                                                                         
Afghanistan                90.2     10.0    7.58     44.9   1610.0       9.44   
Albania                    16.6     28.0    6.55     48.6   9930.0       4.49   
Algeria                    27.3     38.4    4.17     31.4  12900.0      16.10   
Angola                    119.0     62.3    2.85     42.9   5900.0      22.40   
Antigua and Barbuda        10.3     45.5    6.03     58.9  19100.0       1.44   
...                         ...      ...     ...      ...      ...        ...   
Vanuatu                    29.2     46.6    5.25     52.7   2950.0       2.62   
Venezuela                  17.1     28.5    4.91     17.6  16500.0      45.90   
Vietnam                    23.3     72.0    6.84     80.2   4490.0      12.10   
Yemen                      56.3     30.0    5.18     34.4   4480.0      23.60   
Zambia                     83.1     37.0    5.89     30.9   3280.0      14.00   

                     life_expec  total_fer     gdpp  
country                                              
Afghanistan                56.2       5.82    553.0  
Albania                    76.3       1.65   4090.0  
Algeria                    76.5       2.89   4460.0  
Angola                     60.1       6.16   3530.0  
Antigua and Barbuda        76.8       2.13  12200.0  
...                         ...        ...      ...  
Vanuatu                    63.0       3.50   2970.0  
Venezuela                  75.4       2.47  13500.0  
Vietnam                    73.1       1.95   1310.0  
Yemen                      67.5       4.67   1310.0  
Zambia                     52.0       5.40   1460.0  

[167 rows x 9 columns]

In [28]:
df_drop=df.drop(labels=['country','gdpp', 'total_fer'],axis=1)
df_drop.head()

child_mort  exports  health  imports  income  inflation  life_expec
0        90.2     10.0    7.58     44.9    1610       9.44        56.2
1        16.6     28.0    6.55     48.6    9930       4.49        76.3
2        27.3     38.4    4.17     31.4   12900      16.10        76.5
3       119.0     62.3    2.85     42.9    5900      22.40        60.1
4        10.3     45.5    6.03     58.9   19100       1.44        76.8

In [29]:
cols = df_drop.columns.tolist()
cols

['child_mort',
 'exports',
 'health',
 'imports',
 'income',
 'inflation',
 'life_expec']

In [30]:
X = df_drop.iloc[:,1:7].values
y = df_drop.iloc[:,0].values
X

array([[1.00e+01, 7.58e+00, 4.49e+01, 1.61e+03, 9.44e+00, 5.62e+01],
       [2.80e+01, 6.55e+00, 4.86e+01, 9.93e+03, 4.49e+00, 7.63e+01],
       [3.84e+01, 4.17e+00, 3.14e+01, 1.29e+04, 1.61e+01, 7.65e+01],
       ...,
       [7.20e+01, 6.84e+00, 8.02e+01, 4.49e+03, 1.21e+01, 7.31e+01],
       [3.00e+01, 5.18e+00, 3.44e+01, 4.48e+03, 2.36e+01, 6.75e+01],
       [3.70e+01, 5.89e+00, 3.09e+01, 3.28e+03, 1.40e+01, 5.20e+01]])

In [31]:
np.shape(X)

(167, 6)

In [32]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)
X_std

array([[-1.13827979,  0.27908825, -0.08245496, -0.8082454 ,  0.15733622,
        -1.61909203],
       [-0.47965843, -0.09701618,  0.07083669, -0.3753689 , -0.31234747,
         0.64786643],
       [-0.09912164, -0.96607302, -0.64176233, -0.22084447,  0.78927429,
         0.67042323],
       ...,
       [ 1.13030491,  0.0088773 ,  1.38003025, -0.65840354,  0.40973191,
         0.28695762],
       [-0.40647827, -0.59727159, -0.5174718 , -0.65892382,  1.50091625,
        -0.34463279],
       [-0.15034774, -0.33801514, -0.66247742, -0.72135793,  0.59001454,
        -2.09278484]])

In [33]:
X_meaned = X_std - np.mean(X_std , axis = 0)
print('X_meaned: ',X_meaned)
print('------------------------------------------------------------------------------------------------------------------------------------')

print('X.shape: ', X.shape)
print('------------------------------------------------------------------------------------------------------------------------------------')
print('X_meaned.shape: ', X_meaned.shape)
print('------------------------------------------------------------------------------------------------------------------------------------')

cov_mat = np.cov(X_meaned , rowvar = False)   # rowvar = False >> work with X_meaned as transposed

print('cov_mat.shape: ',cov_mat.shape)
print('------------------------------------------------------------------------------------------------------------------------------------')

print('cov_mat: ',cov_mat)
print('------------------------------------------------------------------------------------------------------------------------------------')

eigen_values , eigen_vectors = np.linalg.eigh(cov_mat)

print('eigen_vectors.shape: ',eigen_vectors.shape)
print('------------------------------------------------------------------------------------------------------------------------------------')

print('eigen_values: ',eigen_values)
print('------------------------------------------------------------------------------------------------------------------------------------')


#sort the eigenvalues in descending order
sorted_index = np.argsort(eigen_values)[::-1]
print('sorted_index: ', sorted_index)
print('------------------------------------------------------------------------------------------------------------------------------------')

sorted_eigenvalue = eigen_values[sorted_index]
#similarly sort the eigenvectors 
sorted_eigenvectors = eigen_vectors[:,sorted_index]
n_components = 2 #you can select any number of components.
eigenvector_subset = sorted_eigenvectors[:,0:n_components]
print('eigenvector_subset: ',eigenvector_subset)
print('------------------------------------------------------------------------------------------------------------------------------------')

X_reduced = np.dot(eigenvector_subset.transpose(),X_meaned.transpose()).transpose()
print('X_reduced: ', X_reduced)
print('------------------------------------------------------------------------------------------------------------------------------------')
print('X_reduced shape: ', X_reduced.shape)


X_meaned:  [[-1.13827979  0.27908825 -0.08245496 -0.8082454   0.15733622 -1.61909203]
 [-0.47965843 -0.09701618  0.07083669 -0.3753689  -0.31234747  0.64786643]
 [-0.09912164 -0.96607302 -0.64176233 -0.22084447  0.78927429  0.67042323]
 ...
 [ 1.13030491  0.0088773   1.38003025 -0.65840354  0.40973191  0.28695762]
 [-0.40647827 -0.59727159 -0.5174718  -0.65892382  1.50091625 -0.34463279]
 [-0.15034774 -0.33801514 -0.66247742 -0.72135793  0.59001454 -2.09278484]]
------------------------------------------------------------------------------------------------------------------------------------
X.shape:  (167, 6)
------------------------------------------------------------------------------------------------------------------------------------
X_meaned.shape:  (167, 6)
------------------------------------------------------------------------------------------------------------------------------------
cov_mat.shape:  (6, 6)
------------------------------------------------------------------